//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/Thesis/CarMessage.msg.
//

#ifndef __VEINS_CARMESSAGE_M_H
#define __VEINS_CARMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class CarMessage;
} // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/Thesis/CarMessage.msg:8</tt> by nedtool.
 * <pre>
 * message CarMessage extends BaseFrame1609_4
 * {
 *     // If requesting info
 *     bool request = false;
 * 
 *     // Message TTL
 *     int hopCount = 0;
 * 
 *     string demoData;
 * 
 *     // Address of sender. Default is broadcast
 *     LAddress::L2Type senderAddress = -1;
 * 
 *     // Coordinates of the sender
 *     Coord senderPosition;
 * }
 * </pre>
 */
class VEINS_API CarMessage : public ::veins::BaseFrame1609_4
{
  protected:
    bool request = false;
    int hopCount = 0;
    omnetpp::opp_string demoData;
    LAddress::L2Type senderAddress = -1;
    Coord senderPosition;

  private:
    void copy(const CarMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CarMessage&);

  public:
    CarMessage(const char *name=nullptr, short kind=0);
    CarMessage(const CarMessage& other);
    virtual ~CarMessage();
    CarMessage& operator=(const CarMessage& other);
    virtual CarMessage *dup() const override {return new CarMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getRequest() const;
    virtual void setRequest(bool request);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual const char * getDemoData() const;
    virtual void setDemoData(const char * demoData);
    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<CarMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
    virtual const Coord& getSenderPosition() const;
    virtual Coord& getSenderPositionForUpdate() { return const_cast<Coord&>(const_cast<CarMessage*>(this)->getSenderPosition());}
    virtual void setSenderPosition(const Coord& senderPosition);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CarMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CarMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_CARMESSAGE_M_H

